import React, { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { formatRelativeTime } from "../components/NewsCard";

function generateFullContent(title, summary) {
  const cleanSummary = summary ? summary.replace(/The post .* appeared first on .*/g, "") : "";
  if (cleanSummary.length > 500) {
    return [cleanSummary];
  }
  return [
    cleanSummary || `Reports from the mission control center indicate key developments regarding the latest space flight milestone: "${title}".`,
    `According to operations coordinators close to the project, this development represents a pivotal step forward for the sector, drawing intense interest from scientific bodies and international space agencies alike. Aerospace analysts emphasize that the strategic implications of these telemetry updates could shape upcoming mission protocols as operations teams continue processing data.`,
    `Historically, operations of this magnitude have faced rigorous engineering and communication hurdles. However, recent upgrades to ground-station networks, sensor calibration arrays, and real-time telemetry relays have significantly improved tracking reliability. The ongoing integration of automated analytical tools has also streamlined processing times for science teams on the ground.`,
    `As work continues to progress, subsequent phases will prioritize payload validation and safety checkouts. While launch windows and operational timelines remain subject to atmospheric conditions and orbital windows, the momentum generated by this milestone underscores the expanding scope of modern space exploration. Ongoing updates will be distributed as telemetry is verified.`
  ];
}

export default function ArticleDetail() {
  const { id } = useParams();
  const [item, setItem] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    fetch(`https://api.spaceflightnewsapi.net/v4/articles/${id}/`)
      .then((res) => {
        if (!res.ok) throw new Error("Article not found");
        return res.json();
      })
      .then((data) => {
        setItem(data);
        setLoading(false);
      })
      .catch((err) => {
        console.error(err);
        setError(err.message);
        setLoading(false);
      });
  }, [id]);

  const formatDate = (dateStr) => {
    try {
      const options = { year: "numeric", month: "long", day: "numeric" };
      return new Date(dateStr).toLocaleDateString("en-US", options);
    } catch (e) {
      return "";
    }
  };

  if (loading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center py-20 gap-3">
        <div className="w-8 h-8 border-3 border-accent-red border-t-transparent rounded-full animate-spin"></div>
        <div className="tag-label text-muted-foreground">Retrieving article dispatch...</div>
      </div>
    );
  }

  if (error || !item) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center py-20 px-6 text-center">
        <p className="serif text-xl text-muted-foreground">
          {error || "We could not find the requested article dispatch."}
        </p>
        <Link to="/articles" className="tag-label mt-6 px-4 py-2 bg-foreground text-background cursor-pointer">
          ← Back to Articles
        </Link>
      </div>
    );
  }

  const authorsText = item.authors && item.authors.length > 0
    ? item.authors.map(a => a.name).join(", ")
    : item.news_site;

  return (
    <article className="mx-auto max-w-3xl px-6 py-12 fade-in flex-1">
      {/* Category & Source Header */}
      <div className="tag-label text-accent-red">
        <Link to="/articles" className="hover:underline">articles</Link> · {item.news_site}
      </div>

      {/* Main Title */}
      <h1 className="headline-xl mt-3 text-4xl md:text-6xl text-foreground leading-tight">
        {item.title}
      </h1>

      {/* Author & Timestamp details */}
      <div className="mt-4 tag-label text-muted-foreground">
        <span>By {authorsText} · </span>
        {formatDate(item.published_at)} · {formatRelativeTime(item.published_at)}
      </div>

      {/* Image Banner */}
      <div className="mt-8 aspect-[16/9] overflow-hidden bg-muted">
        <img 
          src={item.image_url} 
          alt={item.title} 
          className="h-full w-full object-cover" 
        />
      </div>

      {/* Summary Content Body */}
      <div className="serif mt-8 text-xl leading-relaxed text-foreground space-y-6">
        {generateFullContent(item.title, item.summary).map((para, idx) => (
          <p key={idx}>{para}</p>
        ))}
      </div>

      {/* Continue Reading Button */}
      <div className="mt-10 rule-top pt-6">
        <a 
          href={item.url} 
          target="_blank" 
          rel="noreferrer" 
          className="article-read-more-btn"
        >
          Read full article at {item.news_site} ↗
        </a>
      </div>
    </article>
  );
}
